spring:
  datasource:
    # This is the line we fixed. Added "&allowPublicKeyRetrieval=true"
    url: jdbc:mysql://localhost:3306/expense_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sivasiva@25
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
jwt:
  secret: replace-me-with-a-long-random-secret
  expiration-ms: 3600000   # 1 hour in milliseconds

app:
  default-currency: INR
